# Generated by Django 5.0.6 on 2024-05-24 13:49

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geodata",
            name="file",
            field=models.FileField(upload_to=backend.models.upload_to_jnr_works),
        ),
    ]
